def create_lender_list_payload(data: dict):
    """
    Prepare lenderList data.
    """
    prepared_data = {
        "sourcePartnerId": data.get("sourcePartnerId"),
        "targetPlatform": data.get("targetPlatforms")[0]["id"],
        "lenderList": data.get("lenderList"),
    }
    return prepared_data


lender_list_sample = {
    "sourcePartnerId": "str",
    "targetPlatforms": [{"id": "str", "partyId": "str"}],
    "financeMethod": "str",
    "customerType": "str",
    "applicant": {
        "relationship": "str",
        "salutation": "str",
        "firstName": "str",
        "lastName": "str",
        "middleName": "str",
        "suffix": "str",
        "phone": "str",
        "address": {
            "line1": "str",
            "line2": "str",
            "city": "str",
            "state": "str",
            "postalCode": "str",
        },
        "protected": {
            "ssn": "str",
            "dateOfBirth": "str",
            "driversLicenseNumber": "str",
            "driversLicenseState": "str",
        },
        "monthsAtCurrentAddress": "Number",
        "otherPhone": "str",
        "email": "str",
        "preferredContactMethod": "str",
        "preferredLanguage": "str",
        "currentEmployment": {
            "employerName": "str",
            "totalMonthsEmployed": "Number",
            "occupation": "str",
            "workPhone": "str",
            "status": "str",
            "employerAddress": {
                "line1": "str",
                "line2": "str",
                "city": "str",
                "state": "str",
                "postalCode": "str",
            },
        },
        "income": "Number",
        "incomeFrequency": "str",
        "otherMonthlyIncome": "Number",
        "otherMonthlyIncomeSource": "str",
        "housingStatus": "str",
        "maritalStatus": "str",
        "mortgageOrRentAmount": "Number",
        "previousAddress": {
            "line1": "str",
            "line2": "str",
            "city": "str",
            "state": "str",
            "postalCode": "str",
        },
        "monthsAtPreviousAddress": "Number",
        "previousEmployment": {
            "employerName": "str",
            "totalMonthsEmployed": "Number",
            "occupation": "str",
            "workPhone": "str",
            "status": "str",
            "employerAddress": {
                "line1": "str",
                "line2": "str",
                "city": "str",
                "state": "str",
                "postalCode": "str",
            },
        },
        "spouse": {
            "firstName": "str",
            "lastName": "str",
            "middleName": "str",
            "suffix": "str",
            "address": {
                "line1": "str",
                "line2": "str",
                "city": "str",
                "state": "str",
                "postalCode": "str",
            },
            "income": "Number",
            "incomeFrequency": "str",
            "otherMonthlyIncome": "Number",
            "otherMonthlyIncomeSource": "str",
        },
        "references": [
            {
                "salutation": "str",
                "firstName": "str",
                "lastName": "str",
                "middleName": "str",
                "suffix": "str",
                "phone": "str",
                "ssn": "str",
                "dateOfBirth": "str",
                "address": {
                    "line1": "str",
                    "line2": "str",
                    "city": "str",
                    "state": "str",
                    "postalCode": "str",
                },
            }
        ],
        "consentGiven": "bool",
    },
    "businessApplicant": "businessApplicant",
    "coApplicant": {
        "relationship": "str",
        "salutation": "str",
        "firstName": "str",
        "lastName": "str",
        "middleName": "str",
        "suffix": "str",
        "phone": "str",
        "address": {
            "line1": "str",
            "line2": "str",
            "city": "str",
            "state": "str",
            "postalCode": "str",
        },
        "protected": {
            "ssn": "str",
            "dateOfBirth": "str",
            "driversLicenseNumber": "str",
            "driversLicenseState": "str",
        },
        "monthsAtCurrentAddress": "Number",
        "otherPhone": "str",
        "email": "str",
        "preferredContactMethod": "str",
        "preferredLanguage": "str",
        "currentEmployment": {
            "employerName": "str",
            "totalMonthsEmployed": "Number",
            "occupation": "str",
            "workPhone": "str",
            "status": "str",
            "employerAddress": {
                "line1": "str",
                "line2": "str",
                "city": "str",
                "state": "str",
                "postalCode": "str",
            },
        },
        "income": "Number",
        "incomeFrequency": "str",
        "otherMonthlyIncome": "Number",
        "otherMonthlyIncomeSource": "str",
        "housingStatus": "str",
        "maritalStatus": "str",
        "mortgageOrRentAmount": "Number",
        "previousAddress": {
            "line1": "str",
            "line2": "str",
            "city": "str",
            "state": "str",
            "postalCode": "str",
        },
        "monthsAtPreviousAddress": "Number",
        "previousEmployment": {
            "employerName": "str",
            "totalMonthsEmployed": "Number",
            "occupation": "str",
            "workPhone": "str",
            "status": "str",
            "employerAddress": {
                "line1": "str",
                "line2": "str",
                "city": "str",
                "state": "str",
                "postalCode": "str",
            },
        },
        "spouse": {
            "firstName": "str",
            "lastName": "str",
            "middleName": "str",
            "suffix": "str",
            "address": {
                "line1": "str",
                "line2": "str",
                "city": "str",
                "state": "str",
                "postalCode": "str",
            },
            "income": "Number",
            "incomeFrequency": "str",
            "otherMonthlyIncome": "Number",
            "otherMonthlyIncomeSource": "str",
        },
        "references": [
            {
                "salutation": "str",
                "firstName": "str",
                "lastName": "str",
                "middleName": "str",
                "suffix": "str",
                "phone": "str",
                "ssn": "str",
                "dateOfBirth": "str",
                "address": {
                    "line1": "str",
                    "line2": "str",
                    "city": "str",
                    "state": "str",
                    "postalCode": "str",
                },
            }
        ],
        "consentGiven": "bool",
    },
    "guarantor": {
        "relationship": "str",
        "salutation": "str",
        "firstName": "str",
        "lastName": "str",
        "middleName": "str",
        "suffix": "str",
        "phone": "str",
        "address": {
            "line1": "str",
            "line2": "str",
            "city": "str",
            "state": "str",
            "postalCode": "str",
        },
        "monthsAtCurrentAddress": "Number",
        "otherPhone": "str",
        "email": "str",
        "preferredContactMethod": "str",
        "preferredLanguage": "str",
        "currentEmployment": {
            "employerName": "str",
            "totalMonthsEmployed": "Number",
            "occupation": "str",
            "workPhone": "str",
            "status": "str",
            "employerAddress": {
                "line1": "str",
                "line2": "str",
                "city": "str",
                "state": "str",
                "postalCode": "str",
            },
        },
        "protected": {
            "ssn": "str",
            "dateOfBirth": "str",
            "driversLicenseNumber": "str",
            "driversLicenseState": "str",
        },
        "income": "Number",
        "incomeFrequency": "str",
        "otherMonthlyIncome": "Number",
        "otherMonthlyIncomeSource": "str",
        "housingStatus": "str",
        "maritalStatus": "str",
        "mortgageOrRentAmount": "Number",
        "previousAddress": {
            "line1": "str",
            "line2": "str",
            "city": "str",
            "state": "str",
            "postalCode": "str",
        },
        "monthsAtPreviousAddress": "Number",
        "previousEmployment": {
            "employerName": "str",
            "totalMonthsEmployed": "Number",
            "occupation": "str",
            "workPhone": "str",
            "status": "str",
            "employerAddress": {
                "line1": "str",
                "line2": "str",
                "city": "str",
                "state": "str",
                "postalCode": "str",
            },
        },
        "spouse": {
            "firstName": "str",
            "lastName": "str",
            "middleName": "str",
            "suffix": "str",
            "address": {
                "line1": "str",
                "line2": "str",
                "city": "str",
                "state": "str",
                "postalCode": "str",
            },
            "income": "Number",
            "incomeFrequency": "str",
            "otherMonthlyIncome": "Number",
            "otherMonthlyIncomeSource": "str",
        },
        "references": [
            {
                "salutation": "str",
                "firstName": "str",
                "lastName": "str",
                "middleName": "str",
                "suffix": "str",
                "phone": "str",
                "ssn": "str",
                "dateOfBirth": "str",
                "address": {
                    "line1": "str",
                    "line2": "str",
                    "city": "str",
                    "state": "str",
                    "postalCode": "str",
                },
            }
        ],
        "consentGiven": "bool",
    },
    "driver": {
        "salutation": "str",
        "firstName": "str",
        "lastName": "str",
        "middleName": "str",
        "phone": "str",
        "suffix": "str",
        "address": {
            "line1": "str",
            "line2": "str",
            "city": "str",
            "state": "str",
            "postalCode": "str",
        },
        "protected": {
            "ssn": "str",
            "dateOfBirth": "str",
            "driversLicenseNumber": "str",
            "driversLicenseState": "str",
        },
    },
    "vehicle": {
        "inventoryVehicleCondition": "str",
        "vin": "str",
        "stockNumber": "str",
        "chromeYear": "Number",
        "chromeMake": "str",
        "chromeModel": "str",
        "chromeStyle": "str",
        "chromeMakeId": "Number",
        "chromeModelId": "Number",
        "chromeStyleId": "Number",
        "otherYear": "Number",
        "otherMake": "str",
        "otherModel": "str",
        "otherTrim": "str",
        "otherOptions": "str",
        "certifiedUsed": "bool",
    },
    "tradeIns": [
        {
            "inventoryVehicleCondition": "str",
            "vin": "str",
            "stockNumber": "str",
            "chromeYear": "Number",
            "chromeMake": "str",
            "chromeModel": "str",
            "chromeStyle": "str",
            "chromeMakeId": "Number",
            "chromeModelId": "Number",
            "chromeStyleId": "Number",
            "otherYear": "Number",
            "otherMake": "str",
            "otherModel": "str",
            "otherTrim": "str",
            "otherOptions": "str",
            "certifiedUsed": "bool",
            "tradeInType": "str",
            "tradeInOwnershipInd": "str",
            "actualCashValue": "Number",
            "monthlyPayment": "Number",
            "payoffAmount": "Number",
            "allowanceAmount": "Number",
            "tradeInLicensePlateNumber": "str",
            "vehicleBookCondition": "str",
            "lienHolder": {
                "name": "str",
                "phone": "str",
                "address": {
                    "line1": "str",
                    "line2": "str",
                    "city": "str",
                    "state": "str",
                    "postalCode": "str",
                },
            },
        }
    ],
    "financeSummary": {
        "vehicleSellingPrice": "Number",
        "salesTax": "Number",
        "governmentFees": "Number",
        "cashDown": "Number",
        "rebate": "Number",
        "creditLifeIns": "Number",
        "term": "Number",
        "requestedAPR": "Number",
        "acquisitionFees": "Number",
        "invoiceAmount": "Number",
        "warranty": "Number",
        "gap": "Number",
        "accidentHealthIns": "Number",
        "frontEndFees": "Number",
        "msrp": "Number",
        "estimatedBalloonAmount": "Number",
        "estimatedPayment": "Number",
        "usedCarBook": "str",
        "mileage": "Number",
        "usedCarValue": "Number",
        "otherFees": "Number",
        "wholesaleBookDetails": [
            {"source": "str", "value": "Number", "condition": "str"}
        ],
        "wholesaleValueType": "str",
        "wholesaleCondition": "str",
        "wholesaleValue": "Number",
        "netTrade": "Number",
    },
    "partnerSource": "str",
    "comments": "str",
    "regulationBIndicator": "bool",
    "privacyNoticeIndicator": "bool",
    "communityPropertyDisclosureIndicator": "bool",
    "extraData": [{"name": "str", "value": "str"}],
    "lenderList": [{"lenderId": "str", "lenderName": "str"}],
}

formatted_dict = {
    "sourcePartnerId": "DWR",
    "targetPlatform": {
         "id": "DTC",
         "partyId": "6663740"
    },
    "lenderList": [
        {
           "lenderId": "BOA",
           "lenderName": "Bank of America"
        },
        {
           "lenderId": "CMB",
           "lenderName": "Chase Bank"
        },
        {
          "lenderId": "DTL",
          "lenderName": "DTL"
        }
     ]
}


def test_create_lender_list_payload():
    """
    Test proper lenderList fields are present
    """
    expected_result = {
        "sourcePartnerId": "str",
        "targetPlatform": "str",
        "lenderList": [
            {
                "lenderId": "str",
                "lenderName": "str"
            }
        ]
    }

    lender_list_data = create_lender_list_payload(lender_list_sample)
    assert expected_result == lender_list_data

